runtime: python27
api_version: 1
threadsafe: yes

handlers:

  - url: /
    static_files: demo/index.html
    upload: demo/index.html
  - url: /favicon\.ico
    static_files: demo/favicon.ico
    upload: demo/favicon\.ico
  - url: /(.*)
    static_files: demo/\1
    upload: demo/(.*)
  - url: /
    static_dir: demo

skip_files:
  - e2e/
  - dist/
  - node_modules/
  - projects/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE